async function init() {
}

init().catch((error) => {
  console.log(error);
});
